# Generated by Django 5.0.6 on 2024-05-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_delete_logindata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
