# Generated by Django 5.0.6 on 2024-05-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_note_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
