# Generated by Django 5.0.6 on 2024-05-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
